### ISSUE TITLE
I don't quite understand the meaning and function of composer configuration in step 4 of v.0.2.0

### ISSUE THREAD

**Issue by gebiwws** [naver/pinpoint-c-agent#122]
Trying to operate from understanding, no data appeared on the result page and no log was fed back after the collector-agent Python program started. Help me

collector-agent config：
[Collector]
AgentID=sit
ApplicationName=deposit-test
CollectorSpanIp=172.16.131.252
CollectorSpanPort=9996
CollectorStatIp=172.16.131.252
CollectorStatPort=9996
CollectorTcpIp=172.16.131.252
CollectorTcpPort=9994
[Common]
# your web server (nginx&apache) port
Web_Port=80
# debug in dev
Log_Level=ERROR
LOG_DIR=/var/log/rockfintech/
[Agent]
# the same as below "pinpoint_php.CollectorHost"
Address=/data/pinpoint-php/collector-agent.sock

PHP ini configure：
extension=pinpoint_php.so
; must be unix:(unix sock address)
pinpoint_php.CollectorHost=unix:/data/pinpoint-php/collector-agent.sock
pinpoint_php.SendSpanTimeOutMs=0
; request should be captured duing 1 second. < 0 means no limited
pinpoint_php.TraceLimit=-1

PHP version 7.1

**Comment by eeliu** [comment]
@gebiwws 
Thanks for the fed back.

I suggested you open the logging.

> collector-agent
collector.conf
```
 Log_Level=ERROR ->   Log_Level=DEBUG
```
> php.ini
```
pinpoint_php.DebugReport=true
```

**Comment by gebiwws** [comment]
Hello:

Open the debug log level and get the following logs:

[2019-08-20 16:27:33,838] [DEBUG] [TCollectorAgent.py:49] CollectorTcp ('172.26.131.252', 9994) CollectorStat ('172.26.131.252', 9996) CollectorSpan ('172.26.131.252', 9996)
[2019-08-20 16:27:33,863] [DEBUG] [AgentStateManager.py:43] register state timer
[2019-08-20 16:27:33,864] [DEBUG] [AgentStateManager.py:56] send state:TAgentStatBatch(agentId='sit', startTimestamp=1566289653838, agentStats=[TAgentStat(agentId='sit', startTimestamp=1566289653838, timestamp=None, collectInterval=None, gc=None, cpuLoad=TCpuLoad(jvmCpuLoad=None, systemCpuLoad=0.3), transaction=None, activeTrace=None, metadata=None)])
[2019-08-20 16:27:33,865] [INFO] [StreamClientLayer.py:124] try to connect:('172.26.131.252', 9994) with timeout:5
[2019-08-20 16:27:33,865] [INFO] [StreamClientLayer.py:71] connect peer: [172.26.131.252:9994] success
[2019-08-20 16:27:33,865] [DEBUG] [TCollectorAgent.py:267] send hand shake len:203
[2019-08-20 16:27:33,865] [DEBUG] [StreamClientLayer.py:171] send 203
[2019-08-20 16:27:33,866] [DEBUG] [TCollectorAgent.py:188] code 0 subcode 2
[2019-08-20 16:27:33,866] [DEBUG] [TCollectorAgent.py:166] register send ping 
[2019-08-20 16:27:33,866] [DEBUG] [TCollectorAgent.py:170]  send agentInfo 
[2019-08-20 16:27:33,867] [DEBUG] [TCollectorAgent.py:298] agent:TAgentInfo(hostname='sit-all-01', ip='172.26.131.191', ports='80', agentId='sit', applicationName='deposit-test', serviceType=1500, pid=14003, agentVersion='1.8.0-RC1', vmVersion=None, startTimestamp=1566289653838, endTimestamp=None, endStatus=None, serverMetaData=None, jvmInfo=None)
[2019-08-20 16:27:33,867] [DEBUG] [TCollectorAgent.py:257] send agentInfo len:91
[2019-08-20 16:27:33,867] [DEBUG] [StreamClientLayer.py:171] send 99
[2019-08-20 16:27:33,868] [DEBUG] [TCollectorAgent.py:224] recv pong
[2019-08-20 16:27:33,869] [DEBUG] [TCollectorAgent.py:204] response: TResult(success=True, message=None)
[2019-08-20 16:27:38,421] [WARNING] [run.py:47] collector agent exit with SIGNAL
[2019-08-20 16:27:54,602] [DEBUG] [TCollectorAgent.py:49] CollectorTcp ('172.26.131.252', 9994) CollectorStat ('172.26.131.252', 9996) CollectorSpan ('172.26.131.252', 9996)
[2019-08-20 16:27:54,627] [DEBUG] [AgentStateManager.py:43] register state timer
[2019-08-20 16:27:54,628] [DEBUG] [AgentStateManager.py:56] send state:TAgentStatBatch(agentId='sit', startTimestamp=1566289674602, agentStats=[TAgentStat(agentId='sit', startTimestamp=1566289674602, timestamp=None, collectInterval=None, gc=None, cpuLoad=TCpuLoad(jvmCpuLoad=None, systemCpuLoad=0.21), transaction=None, activeTrace=None, metadata=None)])
[2019-08-20 16:27:54,629] [INFO] [StreamClientLayer.py:124] try to connect:('172.26.131.252', 9994) with timeout:5
[2019-08-20 16:27:54,629] [INFO] [StreamClientLayer.py:71] connect peer: [172.26.131.252:9994] success
[2019-08-20 16:27:54,629] [DEBUG] [TCollectorAgent.py:267] send hand shake len:203
[2019-08-20 16:27:54,629] [DEBUG] [StreamClientLayer.py:171] send 203
[2019-08-20 16:27:54,630] [DEBUG] [TCollectorAgent.py:188] code 0 subcode 2
[2019-08-20 16:27:54,630] [DEBUG] [TCollectorAgent.py:166] register send ping 
[2019-08-20 16:27:54,630] [DEBUG] [TCollectorAgent.py:170]  send agentInfo 
[2019-08-20 16:27:54,631] [DEBUG] [TCollectorAgent.py:298] agent:TAgentInfo(hostname='sit-all-01', ip='172.26.131.191', ports='80', agentId='sit', applicationName='deposit-test', serviceType=1500, pid=14116, agentVersion='1.8.0-RC1', vmVersion=None, startTimestamp=1566289674602, endTimestamp=None, endStatus=None, serverMetaData=None, jvmInfo=None)
[2019-08-20 16:27:54,631] [DEBUG] [TCollectorAgent.py:257] send agentInfo len:91
[2019-08-20 16:27:54,631] [DEBUG] [StreamClientLayer.py:171] send 99
[2019-08-20 16:27:54,632] [DEBUG] [TCollectorAgent.py:224] recv pong
[2019-08-20 16:27:54,633] [DEBUG] [TCollectorAgent.py:204] response: TResult(success=True, message=None)
[2019-08-20 16:28:04,640] [DEBUG] [StreamClientLayer.py:171] send 8
[2019-08-20 16:28:04,640] [DEBUG] [TCollectorAgent.py:224] recv pong
[2019-08-20 16:28:14,636] [DEBUG] [AgentStateManager.py:56] send state:TAgentStatBatch(agentId='sit', startTimestamp=1566289674602, agentStats=[TAgentStat(agentId='sit', startTimestamp=1566289674602, timestamp=None, collectInterval=None, gc=None, cpuLoad=TCpuLoad(jvmCpuLoad=None, systemCpuLoad=0.15), transaction=None, activeTrace=None, metadata=None)])
[2019-08-20 16:28:14,636] [DEBUG] [StreamClientLayer.py:171] send 8
[2019-08-20 16:28:14,636] [DEBUG] [TCollectorAgent.py:224] recv pong
[2019-08-20 16:28:24,639] [DEBUG] [StreamClientLayer.py:171] send 8
[2019-08-20 16:28:24,640] [DEBUG] [TCollectorAgent.py:224] recv pong

[2019-08-20 16:28:34,633] [DEBUG] [AgentStateManager.py:56] send state:TAgentStatBatch(agentId='sit', startTimestamp=1566289674602, agentStats=[TAgentStat(agentId='sit', startTimestamp=1566289674602, timestamp=None, collectInterval=None, gc=None, cpuLoad=TCpuLoad(jvmCpuLoad=None, systemCpuLoad=0.18), transaction=None, activeTrace=None, metadata=None)])
[2019-08-20 16:28:34,633] [DEBUG] [StreamClientLayer.py:171] send 8
[2019-08-20 16:28:34,633] [DEBUG] [TCollectorAgent.py:224] recv pong
[2019-08-20 16:28:44,638] [DEBUG] [StreamClientLayer.py:171] send 8
[2019-08-20 16:28:44,638] [DEBUG] [TCollectorAgent.py:224] recv pong
[2019-08-20 16:28:46,439] [DEBUG] [StreamClientLayer.py:171] send 2
[2019-08-20 16:28:54,635] [DEBUG] [AgentStateManager.py:56] send state:TAgentStatBatch(agentId='sit', startTimestamp=1566289674602, agentStats=[TAgentStat(agentId='sit', startTimestamp=1566289674602, timestamp=None, collectInterval=None, gc=None, cpuLoad=TCpuLoad(jvmCpuLoad=None, systemCpuLoad=0.13), transaction=None, activeTrace=None, metadata=None)])
[2019-08-20 16:28:54,635] [DEBUG] [StreamClientLayer.py:171] send 8
[2019-08-20 16:28:54,636] [DEBUG] [TCollectorAgent.py:224] recv pong
[2019-08-20 16:29:04,639] [DEBUG] [StreamClientLayer.py:171] send 8
[2019-08-20 16:29:04,639] [DEBUG] [TCollectorAgent.py:224] recv pong
[2019-08-20 16:29:14,637] [DEBUG] [AgentStateManager.py:56] send state:TAgentStatBatch(agentId='sit', startTimestamp=1566289674602, agentStats=[TAgentStat(agentId='sit', startTimestamp=1566289674602, timestamp=None, collectInterval=None, gc=None, cpuLoad=TCpuLoad(jvmCpuLoad=None, systemCpuLoad=0.09), transaction=None, activeTrace=None, metadata=None)])
[2019-08-20 16:29:14,637] [DEBUG] [StreamClientLayer.py:171] send 8
[2019-08-20 16:29:14,637] [DEBUG] [TCollectorAgent.py:224] recv pong
[2019-08-20 16:29:24,640] [DEBUG] [StreamClientLayer.py:171] send 8
[2019-08-20 16:29:24,640] [DEBUG] [TCollectorAgent.py:224] recv pong



I've always wondered where I should specify a site that is actually monitored if there are multiple PHP sites running on a server.

**Comment by lpvus** [comment]
@gebiwws  php.agent.log  Is there a log? 有日志吗？

**Comment by eeliu** [comment]
@gebiwws

From the above, the collector-agent works fine.

While, can you post the php error_log.

```php.ini
; example
error_log=/tmp/php_fpm_error.log
pinpoint_php.DebugReport=true
```

**Comment by eeliu** [comment]
> @gebiwws php.agent.log Is there a log? 有日志吗？

No just for the further.

**Comment by eeliu** [comment]
> I don't quite understand the meaning and function of composer configuration in step 4 of v.0.2.0

After the pinpoint-c-agent deployed success, goto  https://github.com/naver/pinpoint-c-agent/blob/ead06517e68786edc0f8f7895ad10a4984a19e51/PHP/pinpoint_php_example/app/index.php#L9
, and you could know what happens on your code.

**Comment by gebiwws** [comment]
> @gebiwws
> 
> From the above, the collector-agent works fine.
> 
> While, can you post the php error_log.
> 
> ```ini
> ; example
> error_log=/tmp/php_fpm_error.log
> pinpoint_php.DebugReport=true
> ```

The error log that opened PHP did not get any output, and php. agent. log did not get any log output. I wonder if there's something wrong with my operation, if you want collector-agent to be associated with a specific PHP site?

**Comment by eeliu** [comment]
@gebiwws 
Have you enable those lines? 
https://github.com/naver/pinpoint-c-agent/blob/ead06517e68786edc0f8f7895ad10a4984a19e51/PHP/pinpoint_php_example/app/index.php#L8-L12

All the hooks are driven by PHP script, so the easiest way is "echo " in your php project  files.

Blow is the callback when request start

https://github.com/naver/pinpoint-c-agent/blob/ead06517e68786edc0f8f7895ad10a4984a19e51/PHP/pinpoint_php_example/Plugins/PerRequestPlugins.php#L53-L57

**Comment by lpvus** [comment]
@gebiwws  @eeliu 
Modify the permissions of the file
log:
/tmp/collector-agent.sock failed as (Permission denied)

Execute the command：
chmod 777 collector-agent.sock

**Comment by gebiwws** [comment]
> @gebiwws
> 你启用那些线路吗？
> https://github.com/naver/pinpoint-c-agent/blob/ead06517e68786edc0f8f7895ad10a4984a19e51/PHP/pinpoint_php_example/app/index.php#L8-L12
> 
> 所有的钩子都是由PHP脚本驱动的，所以最简单的方法是在php项目文件中使用“echo”。
> 
> Blow是请求启动时的回调
> 
> https://github.com/naver/pinpoint-c-agent/blob/ead06517e68786edc0f8f7895ad10a4984a19e51/PHP/pinpoint_php_example/Plugins/PerRequestPlugins.php#L53-L57

Do you need to copy all the files in the pinpoint-c-agent/PHP/pinpoint_php_example/app directory to the app directory of the PHP site?

**Comment by gebiwws** [comment]
> @gebiwws
> Have you enable those lines?
> https://github.com/naver/pinpoint-c-agent/blob/ead06517e68786edc0f8f7895ad10a4984a19e51/PHP/pinpoint_php_example/app/index.php#L8-L12
> 
> All the hooks are driven by PHP script, so the easiest way is "echo " in your php project files.
> 
> Blow is the callback when request start
> 
> https://github.com/naver/pinpoint-c-agent/blob/ead06517e68786edc0f8f7895ad10a4984a19e51/PHP/pinpoint_php_example/Plugins/PerRequestPlugins.php#L53-L57

Do you need to copy all the files in the pinpoint-c-agent/PHP/pinpoint_php_example/app directory to the app directory of the PHP site?

**Comment by eeliu** [comment]
@gebiwws 

PerRequestPlugins.php: is the hook during request life-cycle
NextSpanPlugin.php: is the hook when you use curl_xxx. 

> while others are used when needed.

https://github.com/naver/pinpoint-c-agent/blob/master/PHP/pinpoint_php_example/Plugins/CommonPlugin.php

If you are playing with the "pinpoint_php_example", all plugins is needed.

**Comment by gebiwws** [comment]
> @gebiwws
> 
> PerRequestPlugins.php: is the hook during request life-cycle
> NextSpanPlugin.php: is the hook when you use curl_xxx.
> 
> > while others are used when needed.
> 
> https://github.com/naver/pinpoint-c-agent/blob/master/PHP/pinpoint_php_example/Plugins/CommonPlugin.php
> 
> If you are playing with the "pinpoint_php_example", all plugins is needed.

**Ask if v0.2.0 monitoring PHP site needs to modify the code of the original project to improve the whole call chain monitoring. This means that the request first goes to collector-agent and then forwards to the PHP site.**

**Comment by gebiwws** [comment]
> @gebiwws @eeliu
> Modify the permissions of the file
> log:
> /tmp/collector-agent.sock failed as (Permission denied)
> 
> Execute the command：
> chmod 777 collector-agent.sock

I tried, but failed. Maybe there is something wrong with my thinking and I have communicated with the R&D staff of the company. Thank

**Comment by eeliu** [comment]
> > @gebiwws
> > PerRequestPlugins.php: is the hook during request life-cycle
> > NextSpanPlugin.php: is the hook when you use curl_xxx.
> > > while others are used when needed.
> > 
> > 
> > https://github.com/naver/pinpoint-c-agent/blob/master/PHP/pinpoint_php_example/Plugins/CommonPlugin.php
> > If you are playing with the "pinpoint_php_example", all plugins is needed.
> 
> **Ask if v0.2.0 monitoring PHP site needs to modify the code of the original project to improve the whole call chain monitoring. This means that the request first goes to collector-agent and then forwards to the PHP site.**




No. 

This chart shows the data flow.
https://github.com/naver/pinpoint-c-agent#pinpoint-c-agent

Pinpoint-php-agent works on the background, and the plugins you wrote captures the information you cared, and **asynchronously** send it to collector-agent.

**Comment by eeliu** [comment]
> I tried, but failed. Maybe there is something wrong with my thinking and I have communicated with the R&D staff of the company. Thank

> /tmp/collector-agent.sock

just a unix socket between pinpoint_php.so and collector-agent. 
You can place it to every where (you must have the permission) !

**Comment by gebiwws** [comment]
> > > @gebiwws
> > > PerRequestPlugins.php: is the hook during request life-cycle
> > > NextSpanPlugin.php: is the hook when you use curl_xxx.
> > > > while others are used when needed.
> > > 
> > > 
> > > https://github.com/naver/pinpoint-c-agent/blob/master/PHP/pinpoint_php_example/Plugins/CommonPlugin.php
> > > If you are playing with the "pinpoint_php_example", all plugins is needed.
> > 
> > 
> > **Ask if v0.2.0 monitoring PHP site needs to modify the code of the original project to improve the whole call chain monitoring. This means that the request first goes to collector-agent and then forwards to the PHP site.**
> 
> No.
> 
> This chart shows the data flow.
> https://github.com/naver/pinpoint-c-agent#pinpoint-c-agent
> 
> Pinpoint-php-agent works on the background, and the plugins you wrote captures the information you cared, and **asynchronously** send it to collector-agent.

I need to continue to work hard, but I haven't found the specific application of this project yet.

**Comment by gebiwws** [comment]
> > > @gebiwws
> > > PerRequestPlugins.php: is the hook during request life-cycle
> > > NextSpanPlugin.php: is the hook when you use curl_xxx.
> > > > while others are used when needed.
> > > 
> > > 
> > > https://github.com/naver/pinpoint-c-agent/blob/master/PHP/pinpoint_php_example/Plugins/CommonPlugin.php
> > > If you are playing with the "pinpoint_php_example", all plugins is needed.
> > 
> > 
> > **Ask if v0.2.0 monitoring PHP site needs to modify the code of the original project to improve the whole call chain monitoring. This means that the request first goes to collector-agent and then forwards to the PHP site.**
> 
> No.
> 
> This chart shows the data flow.
> https://github.com/naver/pinpoint-c-agent#pinpoint-c-agent
> 
> Pinpoint-php-agent works on the background, and the plugins you wrote captures the information you cared, and **asynchronously** send it to collector-agent.

Pinpoint-collector log, I don't know if it's helpful.

2019-08-21 03:05:20 [INFO ](.c.r.t.t.AgentLifeCycleEventHandler) Handle lifecycle event - pinpointServer:DefaultPinpointServer@3258135e(remote:/172.16.131.191:13315, state:RUN_DUPLEX, healthCheckState:RECEIVED), state:Running
2019-08-21 03:05:21 [WARN ](c.n.p.c.s.SendAgentStatService     ) not send flink server. Because FlinkTcpDataSender is null
2019-08-21 03:05:23 [WARN ](c.n.p.c.s.SendAgentStatService     ) not send flink server. Because FlinkTcpDataSender is null
2019-08-21 03:05:23 [WARN ](c.n.p.c.s.SendAgentStatService     ) not send flink server. Because FlinkTcpDataSender is null
2019-08-21 03:05:26 [WARN ](c.n.p.c.s.SendAgentStatService     ) not send flink server. Because FlinkTcpDataSender is null
2019-08-21 03:05:28 [WARN ](c.n.p.c.s.SendAgentStatService     ) not send flink server. Because FlinkTcpDataSender is null
2019-08-21 03:05:30 [WARN ](c.n.p.c.r.t.u.BaseUDPHandlerFactory) Unexpected error. SendSocketAddress:/172.16.131.191 Cause:unsupported header:Header{signature=-17, version=16, type=56} message:DefaultMessage{header=Header{signature=-17, version=16, type=56}, headerEntity=HeaderEntity{entity={}}, data=TAgentStatBatch(agentId:deposit-test, startTimestamp:1566356570750, agentStats:[TAgentStat(agentId:deposit-test, startTimestamp:1566356570750, cpuLoad:TCpuLoad(systemCpuLoad:0.0))])}
java.lang.UnsupportedOperationException: unsupported header:Header{signature=-17, version=16, type=56}
	at com.navercorp.pinpoint.collector.receiver.thrift.SpanDispatchHandler.getSimpleHandler(SpanDispatchHandler.java:56)
	at com.navercorp.pinpoint.collector.receiver.thrift.SpanDispatchHandler.dispatchSendMessage(SpanDispatchHandler.java:62)
	at com.navercorp.pinpoint.collector.receiver.thrift.DelegateDispatchHandler.dispatchSendMessage(DelegateDispatchHandler.java:56)
	at com.navercorp.pinpoint.collector.receiver.thrift.udp.BaseUDPHandlerFactory$DispatchPacket.receive(BaseUDPHandlerFactory.java:97)
	at com.navercorp.pinpoint.collector.receiver.thrift.udp.BaseUDPHandlerFactory$DispatchPacket.receive(BaseUDPHandlerFactory.java:72)
	at com.navercorp.pinpoint.collector.receiver.thrift.udp.Task.run(Task.java:44)
	at com.navercorp.pinpoint.collector.monitor.MonitoredRunnableDecorator$InstrumentedRunnable.run(MonitoredRunnableDecorator.java:113)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-08-21 03:05:30 [INFO ](.c.r.t.t.AgentLifeCycleEventHandler) Handle lifecycle event - pinpointServer:DefaultPinpointServer@3258135e(remote:/172.16.131.191:13315, state:RUN_DUPLEX, healthCheckState:RECEIVED), state:Running
2019-08-21 03:05:32 [WARN ](c.n.p.c.s.SendAgentStatService     ) not send flink server. Because FlinkTcpDataSender is null
2019-08-21 03:05:33 [WARN ](c.n.p.c.s.SendAgentStatService     ) not send flink server. Because FlinkTcpDataSender is null

**Comment by eeliu** [comment]
@gebiwws 

hmm, what do you want me to for you ?

**Comment by gebiwws** [comment]
> @gebiwws
> 
> hmm, what do you want me to for you ?

According to the tutorial deployment, pinpoint-web only shows agent ID without any data. Help me understand the program, confirm which node is in trouble, and finally complete APM monitoring.

**Comment by gebiwws** [comment]
> @gebiwws
> 
> hmm, what do you want me to for you ?

****
![image](https://user-images.githubusercontent.com/44151157/63400549-cf671d00-c406-11e9-84e9-154a35198b5f.png)
I don't understand how PHP composer monitors PHP sites

**Comment by eeliu** [comment]
> @gebiwws
> 
> From the above, the collector-agent works fine.
> 
> While, can you post the php error_log.
> 
> ```ini
> ; example
> error_log=/tmp/php_fpm_error.log
> pinpoint_php.DebugReport=true
> ```

Got it

```
if you have php error.log:
   upload it
else:
   if check "auto_pinpointed.php" is working:
	   php error.log must include the span information
   else：
       How about upload you project (pls just pick some important files)
```

**Comment by eeliu** [comment]
> I don't understand how PHP composer monitors PHP sites

@gebiwws 

> v0.2.0  implements AOP programming think in PHP. And the faster way to know how pinpoint-php works is make the "PHP/pinpoint_php_example" site works. 

After your example site is done, you could trace every step of pinpoint-php-agent.
