### ISSUE TITLE
Stop Pinpoint logging in catalina.out

### ISSUE THREAD

**Issue by amangupta0297** [naver/pinpoint-c-agent#144]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I checked the [documentation](https://github.com/naver/pinpoint-c-agent/wiki),[issues](https://github.com/naver/pinpoint-c-agent/issues) and found no answer

# Expected Behavior

> Please describe the behavior you are expecting

# Current Behavior

> What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System:

* PHP Version:

* php.ini:

* php-fpm or apache:

* pinpoint_agent.conf:

## Failure Logs

Please include any relevant log snippets or files here.

> pinpoint_log.txt  php.log  php-fpm.log etc (Anything could help us )

**Comment by amangupta0297** [comment]
Hi Team,

I want to pinpoint logging into catalina.out. 
How to do that?
and If i want only ERROR logs, instead of WARN in catalina.out
by changing  file pinpoint-agent/lib/log4j.xml, replacing WARN with ERROR will work?
if not, then how to do that.

>>>>>>>>>
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE log4j:configuration SYSTEM "log4j.dtd">
<log4j:configuration xmlns:log4j='http://jakarta.apache.org/log4j/'>

    <appender name="console" class="org.apache.log4j.ConsoleAppender">
        <param name="Threshold" value="WARN"/>
>>>>>>>>>>>>>>

Log's in catalina.out

>>>>>>>>>>
2019-10-12 09:32:34 [WARN ](ecutor@Pinpoint-UdpSpanDataExecutor) Pinpoint-UdpSpanDataExecutor(8-0) doExecute(). Unexpected Error. Cause:Buffer size cannot exceed 65507. (now:40121, input-size:39822
com.navercorp.pinpoint.thrift.io.BufferOverflowException: Buffer size cannot exceed 65507. (now:40121, input-size:39822
	at com.navercorp.pinpoint.thrift.io.UnsafeByteArrayOutputStream.write(UnsafeByteArrayOutputStream.java:99)
	at org.apache.thrift.transport.TIOStreamTransport.write(TIOStreamTransport.java:145)
	at org.apache.thrift.protocol.TCompactProtocol.writeBinary(TCompactProtocol.java:380)
	at org.apache.thrift.protocol.TCompactProtocol.writeString(TCompactProtocol.java:364)
	at com.navercorp.pinpoint.thrift.dto.TIntStringStringValue$TIntStringStringValueStandardScheme.write(TIntStringStringValue.java:503)
	at com.navercorp.pinpoint.thrift.dto.TIntStringStringValue$TIntStringStringValueStandardScheme.write(TIntStringStringValue.java:448)
	at com.navercorp.pinpoint.thrift.dto.TIntStringStringValue.write(TIntStringStringValue.java:384)
	at com.navercorp.pinpoint.thrift.dto.TAnnotationValue.standardSchemeWriteValue(TAnnotationValue.java:503)
	at org.apache.thrift.TUnion$TUnionStandardScheme.write(TUnion.java:244)
	at org.apache.thrift.TUnion$TUnionStandardScheme.write(TUnion.java:213)
>>>>>>>>>>>>>>>>>>

**Comment by eeliu** [comment]
@amangupta0297 

Hi, please recreate this issue on  "https://github.com/naver/pinpoint/issues" and you can get response there.

**Comment by amangupta0297** [comment]
Thanks. Closing this thread.
