### ISSUE TITLE
Laravel Framework: exception: The payload is invalid. 

### ISSUE THREAD

**Issue by kdszh** [naver/pinpoint-c-agent#32]
Hi,
   I try to run the quickstart_pluginin( GetDateInterceptor ) my laravel framework, an exception appears.

> exception: The payload is invalid. in /data/www/mid/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php on line 191

   laravel version: 5.7
   php version: 7.1.13
   LARAVEL_HOME/routes/web.php:  
[web.php.txt](https://github.com/naver/pinpoint-c-agent/files/2417785/web.php.txt)

    pinpoint web :
![ggggg](https://user-images.githubusercontent.com/2100801/46053563-faed7300-c175-11e8-9961-2166275c76d9.png)

**Comment by eeliu** [comment]
@kdszh  
The agent catches the exception (event if user catched it). 
Agent will drop the catched exception in next released.

Thanks

**Comment by ChenGXQQ** [comment]
@baoshengzhu which Pinpoint version do you use? It is good to use 1.8.0 for php agent.

**Comment by baoshengzhu** [comment]
@ChenGXQQ   The version I used was  pinpoint-web-1.7.3.war and pinpoint-collector-1.7.3.war

**Comment by ChenGXQQ** [comment]
@baoshengzhu Please update to 1.8.0. The icon of PHP agent is added at this version.

**Comment by baoshengzhu** [comment]
@ChenGXQQ 
When I use pines-web-1.8.0.war to report an error as follows, do pines-collecto also need to be replaced with 1.8.0?
2018-09-27 13:59:25 [INFO ](o.a.h.h.c.ZooKeeperRegistry        ) ClusterId read in ZooKeeper is null
2018-09-27 13:59:25 [WARN ](o.s.w.c.s.XmlWebApplicationContext ) Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean wi
th name 'hbaseApplicationIndexDao': Unsatisfied dependency expressed through field 'applicationNameMapper'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'applicatio
nNameMapper': Unsatisfied dependency expressed through field 'applicationFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultApplicationFactory': Injection of aut
owired dependencies failed; nested exception is java.lang.IncompatibleClassChangeError: Implementing class
2018-09-27 13:59:25 [INFO ](c.n.p.c.h.HbaseTemplate2           ) HBaseTemplate2.destroy()
2018-09-27 13:59:25 [WARN ](c.n.p.c.h.HbaseTemplate2           ) count -1
2018-09-27 13:59:25 [INFO ](c.n.p.c.h.ConnectionFactoryBean    ) Hbase Connection destroy()
2018-09-27 13:59:25 [INFO ](onManager$HConnectionImplementation) Closing zookeeper sessionid=0x2d01f34f0001d
2018-09-27 13:59:25 [INFO ](o.a.h.h.s.o.a.z.ZooKeeper          ) Session: 0x2d01f34f0001d closed
2018-09-27 13:59:25 [INFO ](o.a.h.h.s.o.a.z.ClientCnxn         ) EventThread shut down
2018-09-27 13:59:25 [INFO ](c.s.u.ThreadPoolExecutorFactoryBean) Shutting down ExecutorService 'hbaseThreadPool'
2018-09-27 13:59:25 [ERROR](o.s.w.c.ContextLoader              ) Context initialization failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'hbaseApplicationIndexDao': Unsatisfied dependency expressed through field 'applicationNameMapper'; nested exception is org.springframework
.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'applicationNameMapper': Unsatisfied dependency expressed through field 'applicationFactory'; nested exception is org.springframework.beans.factory.BeanCreati
onException: Error creating bean with name 'defaultApplicationFactory': Injection of autowired dependencies failed; nested exception is java.lang.IncompatibleClassChangeError: Implementing class
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:588)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:325)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5157)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5680)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1017)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:993)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1296)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:2039)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by baoshengzhu** [comment]
Hi, When I use pines-web-1.8.0.war to report an error as follows:
2018-09-27 14:38:58 [INFO ](o.a.h.h.s.o.a.z.ClientCnxn         ) Session establishment complete on server 10.64.42.209/10.64.42.209:2181, sessionid = 0x2d01f34f00022, negotiated timeout = 40000
2018-09-27 14:38:58 [WARN ](o.s.w.c.s.XmlWebApplicationContext ) Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'hbaseApplicationIndexDao': Unsatisfied dependency expressed through field 'applicationNameMapper'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'applicationNameMapper': Unsatisfied dependency expressed through field 'applicationFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultApplicationFactory': Injection of autowired dependencies failed; nested exception is java.lang.IncompatibleClassChangeError: Implementing class
2018-09-27 14:38:58 [INFO ](c.n.p.c.h.HbaseTemplate2           ) HBaseTemplate2.destroy()
2018-09-27 14:38:58 [WARN ](c.n.p.c.h.HbaseTemplate2           ) count -1
2018-09-27 14:38:58 [INFO ](c.n.p.c.h.ConnectionFactoryBean    ) Hbase Connection destroy()
2018-09-27 14:38:58 [INFO ](onManager$HConnectionImplementation) Closing zookeeper sessionid=0x2d01f34f00022
2018-09-27 14:38:58 [INFO ](o.a.h.h.s.o.a.z.ZooKeeper          ) Session: 0x2d01f34f00022 closed
2018-09-27 14:38:58 [INFO ](o.a.h.h.s.o.a.z.ClientCnxn         ) EventThread shut down
2018-09-27 14:38:58 [INFO ](c.s.u.ThreadPoolExecutorFactoryBean) Shutting down ExecutorService 'hbaseThreadPool'
2018-09-27 14:38:58 [ERROR](o.s.w.c.ContextLoader              ) Context initialization failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'hbaseApplicationIndexDao': Unsatisfied dependency expressed through field 'applicationNameMapper'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'applicationNameMapper': Unsatisfied dependency expressed through field 'applicationFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultApplicationFactory': Injection of autowired dependencies failed; nested exception is java.lang.IncompatibleClassChangeError: Implementing class
    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:588)
    at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
    at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443)
    at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:325)
    at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5157)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5680)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1017)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:993)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
    at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1296)
    at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:2039)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)

**Comment by baoshengzhu** [comment]
@ChenGXQQ 


Hi, When I use pines-web-1.8.0.war to report an error as follows:
2018-09-27 14:38:58 INFO Session establishment complete on server 10.64.42.209/10.64.42.209:2181, sessionid = 0x2d01f34f00022, negotiated timeout = 40000
2018-09-27 14:38:58 WARN Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'hbaseApplicationIndexDao': Unsatisfied dependency expressed through field 'applicationNameMapper'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'applicationNameMapper': Unsatisfied dependency expressed through field 'applicationFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultApplicationFactory': Injection of autowired dependencies failed; nested exception is java.lang.IncompatibleClassChangeError: Implementing class
2018-09-27 14:38:58 INFO HBaseTemplate2.destroy()
2018-09-27 14:38:58 WARN count -1
2018-09-27 14:38:58 INFO Hbase Connection destroy()
2018-09-27 14:38:58 INFO Closing zookeeper sessionid=0x2d01f34f00022
2018-09-27 14:38:58 INFO Session: 0x2d01f34f00022 closed
2018-09-27 14:38:58 INFO EventThread shut down
2018-09-27 14:38:58 INFO Shutting down ExecutorService 'hbaseThreadPool'
2018-09-27 14:38:58 ERROR Context initialization failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'hbaseApplicationIndexDao': Unsatisfied dependency expressed through field 'applicationNameMapper'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'applicationNameMapper': Unsatisfied dependency expressed through field 'applicationFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultApplicationFactory': Injection of autowired dependencies failed; nested exception is java.lang.IncompatibleClassChangeError: Implementing class
at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:588)
at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443)
at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:325)
at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5157)
at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5680)
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1017)
at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:993)
at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1296)
at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:2039)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

**Comment by ChenGXQQ** [comment]
@baoshengzhu 
I don't have this problem. This below is just by guess:
1, collector should be updated with web together
2, 1.8.0 require to set JAVA_9_HOME, please check
Furthermore, if this is still not resolved, you can ask at our main project and I think you will get better answers.

**Comment by baoshengzhu** [comment]
@ChenGXQQ  
Thank you very much. When I upgraded the JDK from 9 to 10, it worked
